keys:
  - &admin_dwt age194jssyfg68srzatkts8e36xe364mvlyan330c7ds6xggwtv5ld9qms829x
  - &server_pi age1tq9x52fylcf0h65jaj3shv3dexsea9z2lz4vnc6mmw9hjatlx4hqfa7fqf
  # - &server_pi_test todo
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *admin_dwt
          - *server_pi
  - path_regex: hosts/pi/secrets.yaml$
    key_groups:
      - age:
          - *admin_dwt
          - *server_pi
  - path_regex: hosts/pi-test/secrets.yaml$
    key_groups:
      - age:
          - *admin_dwt
          # - *server_pi_test
