keys:
  - &admin_dwt age1pxzu64mk3kqwhdtf2rhdymjwf90687cskldgz9rf8puac4l9wdjqevpwt6
  - &server_pi age1kfj5g2jcl3qx4jdpcsl30gu3thn06fmvl0uc888efcd5hrku9cpsckw46m
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *admin_dwt
          - *server_pi
