services:
  lix:
    # privileged: true
    security_opt:
      - seccomp:unconfined
    image: ghcr.io/lix-project/lix:2.91
    volumes:
      - .:/src
    command: /src/bin/build-sd-image.sh
    working_dir: /src
    environment:
      - NIX_DISTRIBUTION=lix

  nix:
    image: nixos/nix:latest
    volumes:
      - .:/src
    command: /src/bin/build-sd-image.sh
    working_dir: /src
    environment:
      - NIX_DISTRIBUTION=nix
